@extends('layouts.app')
@section('title','Admin dashboard')
@section('content')
<div class="admin-shell"><div class="admin-heading"><div><span class="section-kicker">OVERVIEW</span><h1>Membership dashboard</h1><p>Manage your community register and member details.</p></div><a href="{{ route('admin.profile') }}" class="admin-user"><span class="user-avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><span><b>{{ auth()->user()->name }}</b><small>Administrator</small></span></a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<div class="stat-grid"><div class="stat-card surface"><span class="stat-icon">♧</span><small>TOTAL MEMBERS</small><b>{{ number_format($total) }}</b><span class="stat-foot">Registered community members</span></div><div class="stat-card surface"><span class="stat-icon stat-icon-gold">✦</span><small>ADDED TODAY</small><b>{{ number_format($today) }}</b><span class="stat-foot">New registrations today</span></div></div>
<section class="surface table-card"><div class="table-heading"><div><h2>Member records</h2><p>View, print, edit or remove a member entry.</p></div></div><div class="table-tools"><form class="per-page-form" method="GET" action="{{ route('admin.dashboard') }}"><label class="per-page-control">Show <select name="per_page" aria-label="Records per page" onchange="this.form.submit()"><option value="10" @selected($pageSize === '10')>10</option><option value="50" @selected($pageSize === '50')>50</option><option value="100" @selected($pageSize === '100')>100</option><option value="all" @selected($pageSize === 'all')>All</option></select><span>records</span></label>@if(request('q'))<input type="hidden" name="q" value="{{ request('q') }}">@endif</form><form class="search-form" method="GET" action="{{ route('admin.dashboard') }}"><input type="hidden" name="per_page" value="{{ $pageSize }}"><div class="search-input-wrap"><input type="search" name="q" value="{{ request('q') }}" placeholder="Search name or mobile" aria-label="Search by name or mobile">@if(request('q'))<a class="clear-search" href="{{ route('admin.dashboard', ['per_page' => $pageSize]) }}" aria-label="Clear search" title="Clear search">×</a>@endif</div><button class="button button-soft" type="submit">Search</button></form></div>
<div class="table-scroll"><table><thead><tr><th>MEMBER</th><th>MOBILE</th><th>COMMUNITY ROLE</th><th>JOINED</th><th></th></tr></thead><tbody>@forelse($members as $member)<tr><td><div class="member-cell">@if($member->photo)<img src="{{ Storage::url($member->photo) }}" alt="">@else<span class="table-avatar">{{ strtoupper(substr($member->name,0,1)) }}</span>@endif<div><b>{{ $member->name }}</b><small>{{ $member->email ?: 'No email provided' }}</small></div></div></td><td>{{ $member->mobile }}</td><td><span class="role-pill">{{ $member->role ?: '—' }}</span></td><td>{{ $member->created_at->format('d M Y') }}</td><td><div class="row-actions"><a href="{{ route('admin.members.show',$member) }}">View</a><a href="{{ route('admin.members.edit',$member) }}">Edit</a><form method="POST" action="{{ route('admin.members.destroy',$member) }}" onsubmit="return confirm('Delete this member record?')">@csrf @method('DELETE')<button>Delete</button></form></div></td></tr>@empty<tr><td colspan="5" class="empty-row">No member records found. @if(request('q'))Try a different search.@endif</td></tr>@endforelse</tbody></table></div><div class="pagination-wrap">{{ $members->links() }}</div></section></div>
@endsection
