@extends('layouts.app')
@section('title','Admin documents')
@section('content')
<div class="admin-shell"><div class="admin-heading"><div><span class="section-kicker">ADMIN LIBRARY</span><h1>Documents</h1><p>Upload and manage files for your organization.</p></div><a href="{{ route('admin.dashboard') }}" class="button button-soft">← Dashboard</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif
<section class="surface document-upload"><div class="document-upload-icon">↥</div><div><h2>Upload a document</h2><p>Any file type · Maximum file size 50 MB</p></div><form method="POST" action="{{ route('admin.documents.store') }}" enctype="multipart/form-data" class="document-form">@csrf<label class="field"><span>Document title <small>(optional)</small></span><input name="title" value="{{ old('title') }}" maxlength="190" placeholder="Uses the original filename if blank"></label><label class="field"><span>Description <small>(optional)</small></span><textarea name="description" rows="2" maxlength="2000" placeholder="A short note about this file">{{ old('description') }}</textarea></label><label class="field"><span>Choose file</span><input class="document-file" type="file" name="document" required><small class="hint">Files are stored privately and only administrators can download them.</small></label><button class="button button-primary" type="submit">Upload document <span>↑</span></button></form></section>
<section class="surface table-card document-table"><div class="table-heading"><div><h2>Stored documents</h2><p>{{ $documents->total() }} {{ Str::plural('file', $documents->total()) }}</p></div></div><div class="table-scroll"><table><thead><tr><th>DOCUMENT</th><th>FILE TYPE</th><th>SIZE</th><th>UPLOADED</th><th></th></tr></thead><tbody>@forelse($documents as $document)<tr><td><div class="document-name"><span class="document-file-icon">▤</span><div><b>{{ $document->title }}</b><small>{{ $document->original_name }}@if($document->description) · {{ $document->description }}@endif</small></div></div></td><td>{{ $document->mime_type ?: 'Unknown' }}</td><td>{{ number_format($document->size / 1024, $document->size < 1048576 ? 0 : 1) }} KB</td><td>{{ $document->created_at->format('d M Y') }}</td><td><div class="row-actions"><a href="{{ route('admin.documents.download',$document) }}">Download</a><form method="POST" action="{{ route('admin.documents.destroy',$document) }}" onsubmit="return confirm('Delete this document permanently?')">@csrf @method('DELETE')<button>Delete</button></form></div></td></tr>@empty<tr><td colspan="5" class="empty-row">No documents uploaded yet.</td></tr>@endforelse</tbody></table></div><div class="pagination-wrap">{{ $documents->links() }}</div></section></div>
@endsection
